// dashboard/frontend/src/components/leads/LeadModal.jsx
import { useState } from 'react'
import { motion } from 'framer-motion'
import { X, Trash2, Euro, Mail, Phone, Tag, UserCheck } from 'lucide-react'

const PIPELINE_COLUMNS = [
  { id: 'novo', label: 'Novo', color: '#6B7280', icon: '🔵' },
  { id: 'contatado', label: 'Contatado', color: '#3B82F6', icon: '📞' },
  { id: 'proposta_enviada', label: 'Proposta', color: '#F59E0B', icon: '📄' },
  { id: 'negociacao', label: 'Negociacao', color: '#8B5CF6', icon: '🤝' },
  { id: 'ganho', label: 'Ganho', color: '#22C55E', icon: '✅' },
  { id: 'perdido', label: 'Perdido', color: '#EF4444', icon: '❌' },
]

const FOUNDERS = [
  { id: 'abner', name: 'Abner', color: '#3742fa', emoji: '🧠' },
  { id: 'enoque', name: 'Enoque', color: '#2ed573', emoji: '⚡' },
  { id: 'elias', name: 'Elias', color: '#ffa502', emoji: '🎯' },
]

export default function LeadModal({ lead, onClose, onSave, onDelete, onConvert, isConverting }) {
  const [editMode, setEditMode] = useState(!lead)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState(null)
  const [form, setForm] = useState({
    displayName: lead?.displayName || '',
    email: lead?.email || '',
    phone: lead?.phone || '',
    source: lead?.source || 'referral',
    pipelineStatus: lead?.pipelineStatus || 'novo',
    estimatedValue: lead?.estimatedValue || '',
    notes: lead?.notes || '',
    assignedTo: lead?.assignedTo || '',
    tags: lead?.tags?.join(', ') || ''
  })

  const handleSubmit = async (e) => {
    e.preventDefault()
    setError(null)
    setIsSubmitting(true)
    try {
      await onSave({
        ...form,
        estimatedValue: Number(form.estimatedValue) || 0,
        tags: form.tags.split(',').map(t => t.trim()).filter(Boolean)
      })
    } catch (err) {
      setError(err.response?.data?.error || err.message || 'Erro ao salvar lead')
    } finally {
      setIsSubmitting(false)
    }
  }

  const founder = FOUNDERS.find(f => f.id === lead?.assignedTo)
  const statusCol = PIPELINE_COLUMNS.find(c => c.id === lead?.pipelineStatus)

  const renderViewMode = () => (
    <div className="p-4 space-y-4">
      <div className="space-y-3">
        <div className="flex items-center gap-2">
          <span className="text-2xl">{statusCol?.icon}</span>
          <div>
            <div className="text-sm font-medium">{statusCol?.label || lead?.pipelineStatus}</div>
            <div className="text-[10px] text-nexo-muted uppercase tracking-wider">Status</div>
          </div>
        </div>
        {founder && (
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full flex items-center justify-center text-sm" style={{ backgroundColor: founder.color + '30', color: founder.color }}>
              {founder.emoji}
            </div>
            <div>
              <div className="text-sm font-medium">{founder.name}</div>
              <div className="text-[10px] text-nexo-muted uppercase tracking-wider">Responsável</div>
            </div>
          </div>
        )}
        {lead?.estimatedValue > 0 && (
          <div className="flex items-center gap-2">
            <Euro size={18} className="text-nexo-success" />
            <div>
              <div className="text-sm font-medium">€{lead.estimatedValue.toLocaleString('pt-BR')}</div>
              <div className="text-[10px] text-nexo-muted uppercase tracking-wider">Valor Estimado</div>
            </div>
          </div>
        )}
        {lead?.email && (
          <div className="flex items-center gap-2">
            <Mail size={18} className="text-nexo-info" />
            <div>
              <div className="text-sm font-medium">{lead.email}</div>
              <div className="text-[10px] text-nexo-muted uppercase tracking-wider">Email</div>
            </div>
          </div>
        )}
        {lead?.phone && (
          <div className="flex items-center gap-2">
            <Phone size={18} className="text-nexo-info" />
            <div>
              <div className="text-sm font-medium">{lead.phone}</div>
              <div className="text-[10px] text-nexo-muted uppercase tracking-wider">Telefone</div>
            </div>
          </div>
        )}
        {lead?.source && (
          <div className="flex items-center gap-2">
            <Tag size={18} className="text-nexo-muted" />
            <div>
              <div className="text-sm font-medium capitalize">{lead.source.replace(/-/g, ' ')}</div>
              <div className="text-[10px] text-nexo-muted uppercase tracking-wider">Fonte</div>
            </div>
          </div>
        )}
        {lead?.tags?.length > 0 && (
          <div className="flex flex-wrap gap-1 pt-1">
            {lead.tags.map((tag, i) => (
              <span key={i} className="text-[10px] px-2 py-0.5 rounded-full bg-nexo-primary/20 text-nexo-primary">{tag}</span>
            ))}
          </div>
        )}
        {lead?.notes && (
          <div className="glass-card p-3 rounded-lg">
            <div className="text-[10px] text-nexo-muted uppercase tracking-wider mb-1">Notas</div>
            <p className="text-sm text-nexo-text whitespace-pre-wrap">{lead.notes}</p>
          </div>
        )}
      </div>
    </div>
  )

  const renderEditMode = () => (
    <form onSubmit={handleSubmit} className="p-4 space-y-3">
      <div>
        <label className="text-xs text-nexo-muted block mb-1">Nome *</label>
        <input
          required
          value={form.displayName}
          onChange={e => setForm({ ...form, displayName: e.target.value })}
          className="w-full px-3 py-2 bg-nexo-bg border border-nexo-border rounded-lg text-sm text-nexo-text focus:outline-none focus:border-nexo-primary"
        />
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="text-xs text-nexo-muted block mb-1">Email</label>
          <input
            type="email"
            value={form.email}
            onChange={e => setForm({ ...form, email: e.target.value })}
            className="w-full px-3 py-2 bg-nexo-bg border border-nexo-border rounded-lg text-sm text-nexo-text focus:outline-none focus:border-nexo-primary"
          />
        </div>
        <div>
          <label className="text-xs text-nexo-muted block mb-1">Telefone</label>
          <input
            value={form.phone}
            onChange={e => setForm({ ...form, phone: e.target.value })}
            className="w-full px-3 py-2 bg-nexo-bg border border-nexo-border rounded-lg text-sm text-nexo-text focus:outline-none focus:border-nexo-primary"
          />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="text-xs text-nexo-muted block mb-1">Fonte</label>
          <select
            value={form.source}
            onChange={e => setForm({ ...form, source: e.target.value })}
            className="w-full px-3 py-2 bg-nexo-bg border border-nexo-border rounded-lg text-sm text-nexo-text focus:outline-none focus:border-nexo-primary"
          >
            <option value="referral">Indicação</option>
            <option value="whatsapp">WhatsApp</option>
            <option value="email">Email</option>
            <option value="instagram">Instagram</option>
            <option value="prospeccao-interna">Prospecção Interna</option>
            <option value="lead-detectado">Detectado pela Luna</option>
            <option value="manual">Manual</option>
          </select>
        </div>
        <div>
          <label className="text-xs text-nexo-muted block mb-1">Status</label>
          <select
            value={form.pipelineStatus}
            onChange={e => setForm({ ...form, pipelineStatus: e.target.value })}
            className="w-full px-3 py-2 bg-nexo-bg border border-nexo-border rounded-lg text-sm text-nexo-text focus:outline-none focus:border-nexo-primary"
          >
            {PIPELINE_COLUMNS.map(c => (
              <option key={c.id} value={c.id}>{c.icon} {c.label}</option>
            ))}
          </select>
        </div>
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="text-xs text-nexo-muted block mb-1">Valor Estimado (€)</label>
          <input
            type="number"
            value={form.estimatedValue}
            onChange={e => setForm({ ...form, estimatedValue: e.target.value })}
            className="w-full px-3 py-2 bg-nexo-bg border border-nexo-border rounded-lg text-sm text-nexo-text focus:outline-none focus:border-nexo-primary"
          />
        </div>
        <div>
          <label className="text-xs text-nexo-muted block mb-1">Responsável</label>
          <select
            value={form.assignedTo}
            onChange={e => setForm({ ...form, assignedTo: e.target.value })}
            className="w-full px-3 py-2 bg-nexo-bg border border-nexo-border rounded-lg text-sm text-nexo-text focus:outline-none focus:border-nexo-primary"
          >
            <option value="">Não atribuído</option>
            {FOUNDERS.map(f => (
              <option key={f.id} value={f.id}>{f.emoji} {f.name}</option>
            ))}
          </select>
        </div>
      </div>
      <div>
        <label className="text-xs text-nexo-muted block mb-1">Tags (separadas por vírgula)</label>
        <input
          value={form.tags}
          onChange={e => setForm({ ...form, tags: e.target.value })}
          placeholder="site, ecommerce, urgente"
          className="w-full px-3 py-2 bg-nexo-bg border border-nexo-border rounded-lg text-sm text-nexo-text focus:outline-none focus:border-nexo-primary"
        />
      </div>
      <div>
        <label className="text-xs text-nexo-muted block mb-1">Notas</label>
        <textarea
          value={form.notes}
          onChange={e => setForm({ ...form, notes: e.target.value })}
          rows={3}
          className="w-full px-3 py-2 bg-nexo-bg border border-nexo-border rounded-lg text-sm text-nexo-text focus:outline-none focus:border-nexo-primary resize-none"
        />
      </div>
      {error && (
        <div className="px-4 py-2 bg-red-500/10 border border-red-500/30 rounded-lg text-xs text-red-400">
          {error}
        </div>
      )}
      <div className="flex justify-end gap-2 pt-2">
        <button
          type="button"
          onClick={onClose}
          disabled={isSubmitting}
          className="px-4 py-2 text-nexo-muted hover:text-nexo-text text-sm transition-colors disabled:opacity-50"
        >
          Cancelar
        </button>
        <button
          type="submit"
          disabled={isSubmitting || !form.displayName.trim()}
          className="px-4 py-2 bg-nexo-primary rounded-lg text-sm hover:opacity-90 transition-opacity disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isSubmitting ? 'Salvando...' : (lead ? 'Salvar' : 'Criar Lead')}
        </button>
      </div>
    </form>
  )

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.95, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.95, opacity: 0 }}
        className="w-full max-w-lg bg-nexo-card border border-nexo-border rounded-2xl overflow-hidden max-h-[90vh] overflow-y-auto"
        onClick={e => e.stopPropagation()}
      >
        <div className="p-4 border-b border-nexo-border flex items-center justify-between">
          <h3 className="font-semibold">{lead ? lead.displayName : 'Novo Lead'}</h3>
          <div className="flex items-center gap-2">
            {lead && (
              <button
                onClick={() => onDelete(lead.id)}
                className="text-nexo-danger hover:opacity-80 text-xs flex items-center gap-1 px-2 py-1 rounded hover:bg-nexo-danger/10"
              >
                <Trash2 size={14} /> Apagar
              </button>
            )}
            {lead && (
              <button
                onClick={() => setEditMode(!editMode)}
                className="text-nexo-primary hover:opacity-80 text-xs px-2 py-1 rounded hover:bg-nexo-primary/10"
              >
                {editMode ? 'Ver' : 'Editar'}
              </button>
            )}
            {lead && lead.pipelineStatus !== 'ganho' && onConvert && (
              <button
                onClick={() => {
                  if (confirm('Converter este lead em cliente? Isso criará um workspace.')) {
                    onConvert(lead.id)
                  }
                }}
                disabled={isConverting}
                className="text-nexo-success hover:opacity-80 text-xs flex items-center gap-1 px-2 py-1 rounded hover:bg-nexo-success/10 disabled:opacity-50"
              >
                <UserCheck size={14} />
                {isConverting ? 'Convertendo...' : 'Converter'}
              </button>
            )}
            <button onClick={onClose} className="text-nexo-muted hover:text-nexo-text">
              <X size={18} />
            </button>
          </div>
        </div>
        {lead && !editMode ? renderViewMode() : renderEditMode()}
      </motion.div>
    </motion.div>
  )
}

// luna-kernel/luna-web/src/components/LeadModal.svelte
<script>
  import { onMount } from 'svelte';
  
  export let open = false;
  export let onClose = () => {};
  
  let name = '';
  let email = '';
  let phone = '';
  let source = 'site';
  let status = 'novo';
  let value = '';
  let notes = '';
  let loading = false;
  let success = false;
  let error = '';
  
  const sources = [
    { value: 'site', label: 'Site' },
    { value: 'indicacao', label: 'Indicação' },
    { value: 'social', label: 'Redes Sociais' },
    { value: 'anuncio', label: 'Anúncio' },
    { value: 'outro', label: 'Outro' },
  ];
  
  const statuses = [
    { value: 'novo', label: 'Novo' },
    { value: 'contatado', label: 'Contatado' },
    { value: 'proposta_enviada', label: 'Proposta Enviada' },
    { value: 'negociacao', label: 'Negociação' },
    { value: 'ganho', label: 'Ganho' },
    { value: 'perdido', label: 'Perdido' },
  ];
  
  async function handleSubmit() {
    if (!name.trim()) {
      error = 'Nome é obrigatório';
      return;
    }
    loading = true;
    error = '';
    
    try {
      const res = await fetch('/api/leads', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: name.trim(),
          email: email.trim() || undefined,
          phone: phone.trim() || undefined,
          source,
          status,
          value: value ? parseFloat(value) : undefined,
          notes: notes.trim() || undefined,
        })
      });
      
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || 'Erro ao criar lead');
      }
      
      success = true;
      setTimeout(() => {
        reset();
        onClose();
      }, 1500);
    } catch (e) {
      error = e.message;
    } finally {
      loading = false;
    }
  }
  
  function reset() {
    name = '';
    email = '';
    phone = '';
    source = 'site';
    status = 'novo';
    value = '';
    notes = '';
    success = false;
    error = '';
  }
  
  function handleBackdropClick(e) {
    if (e.target === e.currentTarget) {
      onClose();
    }
  }
  
  $: if (!open) reset();
</script>

{#if open}
  <!-- svelte-ignore a11y-click-events-have-key-events -->
  <!-- svelte-ignore a11y-no-static-element-interactions -->
  <div class="modal-backdrop" on:click={handleBackdropClick}>
    <div class="modal-container">
      <div class="modal-header">
        <h2 class="modal-title">🎯 Novo Lead</h2>
        <button class="modal-close" on:click={onClose} aria-label="Fechar">×</button>
      </div>
      
      <div class="modal-body">
        {#if success}
          <div class="success-state">
            <div class="success-icon">✅</div>
            <div class="success-text">Lead criado com sucesso!</div>
          </div>
        {:else}
          <div class="form-grid">
            <div class="form-group">
              <label>Nome *</label>
              <input type="text" bind:value={name} placeholder="Nome do lead" class="form-input" />
            </div>
            
            <div class="form-group">
              <label>Email</label>
              <input type="email" bind:value={email} placeholder="email@exemplo.com" class="form-input" />
            </div>
            
            <div class="form-group">
              <label>Telefone</label>
              <input type="tel" bind:value={phone} placeholder="+55 11 99999-9999" class="form-input" />
            </div>
            
            <div class="form-group">
              <label>Valor</label>
              <input type="number" bind:value={value} placeholder="0,00" min="0" step="0.01" class="form-input" />
            </div>
            
            <div class="form-group">
              <label>Fonte</label>
              <select bind:value={source} class="form-select">
                {#each sources as s}
                  <option value={s.value}>{s.label}</option>
                {/each}
              </select>
            </div>
            
            <div class="form-group">
              <label>Status</label>
              <select bind:value={status} class="form-select">
                {#each statuses as s}
                  <option value={s.value}>{s.label}</option>
                {/each}
              </select>
            </div>
          </div>
          
          <div class="form-group full-width">
            <label>Observações</label>
            <textarea bind:value={notes} placeholder="Notas sobre o lead..." rows="3" class="form-textarea"></textarea>
          </div>
          
          {#if error}
            <div class="form-error">{error}</div>
          {/if}
        {/if}
      </div>
      
      {#if !success}
        <div class="modal-footer">
          <button class="btn-secondary" on:click={onClose}>Cancelar</button>
          <button class="btn-primary" on:click={handleSubmit} disabled={loading || !name.trim()}>
            {loading ? 'Salvando...' : 'Criar Lead'}
          </button>
        </div>
      {/if}
    </div>
  </div>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.6);
    backdrop-filter: blur(8px);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 200;
    padding: 24px;
  }
  .modal-container {
    background: linear-gradient(180deg, #1a1a2e 0%, #12121f 100%);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 20px;
    width: 100%;
    max-width: 520px;
    max-height: 90vh;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    box-shadow: 0 24px 64px rgba(0, 0, 0, 0.5), 0 0 40px rgba(168, 85, 247, 0.08);
  }
  .modal-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 20px 24px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.06);
  }
  .modal-title {
    font-size: 18px;
    font-weight: 600;
    color: var(--luna-text);
    margin: 0;
  }
  .modal-close {
    background: none;
    border: none;
    color: var(--luna-text-secondary);
    font-size: 24px;
    cursor: pointer;
    padding: 4px;
    border-radius: 8px;
    transition: all 0.15s;
    line-height: 1;
  }
  .modal-close:hover {
    background: rgba(255, 255, 255, 0.06);
    color: var(--luna-text);
  }
  .modal-body {
    padding: 24px;
    overflow-y: auto;
    flex: 1;
  }
  .form-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
  }
  .form-group {
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .form-group.full-width {
    grid-column: 1 / -1;
    margin-top: 16px;
  }
  .form-group label {
    font-size: 13px;
    font-weight: 500;
    color: var(--luna-text-secondary);
  }
  .form-input,
  .form-select,
  .form-textarea {
    background: rgba(255, 255, 255, 0.04);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 10px;
    padding: 10px 14px;
    color: var(--luna-text);
    font-size: 14px;
    outline: none;
    transition: all 0.2s;
    width: 100%;
    box-sizing: border-box;
  }
  .form-input:focus,
  .form-select:focus,
  .form-textarea:focus {
    border-color: var(--luna-accent);
    box-shadow: 0 0 0 3px var(--luna-accent-glow);
  }
  .form-select {
    cursor: pointer;
  }
  .form-select option {
    background: #1a1a2e;
    color: var(--luna-text);
  }
  .form-textarea {
    resize: vertical;
    min-height: 80px;
    font-family: inherit;
  }
  .form-error {
    margin-top: 12px;
    padding: 10px 14px;
    background: rgba(231, 76, 60, 0.1);
    border: 1px solid rgba(231, 76, 60, 0.2);
    border-radius: 10px;
    color: #e74c3c;
    font-size: 13px;
  }
  .modal-footer {
    display: flex;
    justify-content: flex-end;
    gap: 12px;
    padding: 16px 24px;
    border-top: 1px solid rgba(255, 255, 255, 0.06);
  }
  .btn-primary,
  .btn-secondary {
    padding: 10px 20px;
    border-radius: 10px;
    font-size: 14px;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s;
    border: none;
  }
  .btn-primary {
    background: var(--luna-accent);
    color: white;
  }
  .btn-primary:hover:not(:disabled) {
    opacity: 0.9;
    transform: translateY(-1px);
  }
  .btn-primary:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .btn-secondary {
    background: rgba(255, 255, 255, 0.06);
    color: var(--luna-text-secondary);
    border: 1px solid rgba(255, 255, 255, 0.08);
  }
  .btn-secondary:hover {
    background: rgba(255, 255, 255, 0.1);
    color: var(--luna-text);
  }
  .success-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 12px;
    padding: 32px 0;
  }
  .success-icon {
    font-size: 48px;
  }
  .success-text {
    font-size: 16px;
    font-weight: 500;
    color: var(--luna-text);
  }
  @media (max-width: 640px) {
    .form-grid {
      grid-template-columns: 1fr;
    }
    .modal-container {
      max-width: 100%;
      border-radius: 16px 16px 0 0;
      max-height: 85vh;
    }
    .modal-backdrop {
      align-items: flex-end;
      padding: 0;
    }
  }
</style>
